### ISSUE TITLE
Missing io.ReaderAt interface

### ISSUE THREAD

**Issue by janekolszak** [djherbis/buffer#10]
Hi! Great library, thank you so much for sharing!

Would it be very hard to add a io.ReaderAt interface to Buffer?
This way Buffer could be used directly for example by the zip package.

Thanks!

**Comment by djherbis** [comment]
@janekolszak There is [BufferAt](https://godoc.org/github.com/djherbis/buffer#BufferAt) which a number of buffers implement. Is there a particular one you wanted?

**Comment by janekolszak** [comment]
There's another issue that I missed when I created this one. I need ReaderAt on Partition to pass it to the zip package.
